version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakephp-app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    environment:
      - CAKE_ENV=development
    command: >
      /bin/bash -c "
      composer install &&
      bin/cake migrations migrate &&
      bin/cake cache clear_all &&
      echo '***************** Application running at http://localhost:8080/ *****************' &&
      apache2-foreground"
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pixelfederation
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
